# Generated by Django 5.1.6 on 2025-02-12 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_comm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='E_comm.category'),
        ),
        migrations.AddField(
            model_name='items',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Prod_Images'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
